version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER: guest
      - RABBITMQ_DEFAULT_PASS : guest
  
  order-service:
   build : ./order-services
   depends_on :
     - rabbitmq
  
  inventory-service:
   build : ./inventory-service
   depends_on:
    - rabbitmq
  
  notification-service:
   build : ./notification-service
   depends_on:
    - rabbitmq